# Generated by Django 5.0.3 on 2024-04-09 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_comment_recomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='post',
            new_name='parent_comment',
        ),
        migrations.AddField(
            model_name='recomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
