# Generated by Django 5.0.3 on 2024-04-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
